version: '3'

services:
   db:
     image: mysql:5.7
     container_name : mysqldb
     volumes:
       - ./data:/var/lib/mysql
     restart: always
     ports:
       - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     container_name : wp
#     depends_on:
#       - db
     image: wordpress:latest
     ports:
       - "80:80"
     restart: always
     volumes:
       - ./www:/var/www/html
     environment:
       WORDPRESS_DB_HOST: db
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
